"""Generate spot_rl_policy_slim.py -- numpy-only (no torch / SB3 / qpsolvers / gymnasium).

It takes spot_env's pure-numpy head (constants + CBF/CLF helpers, everything BEFORE the
gym class), strips the 3 heavy imports, and appends a .mat-weights policy. So the obs
builder is the SAME code as training and can't drift.
"""
import re

src = open("spot_env.py").read().splitlines(keepends=True)
cut = next(i for i, l in enumerate(src) if l.startswith("class SpotDockEnv"))
head = [l for l in src[:cut]
        if not re.match(r"(import gymnasium|from gymnasium|from qpsolvers)", l)]

SLIM = r'''

# ===================== slim policy (numpy-only, .mat weights) =====================
import os as _os
import scipy.io as _sio

_HERE = _os.path.dirname(_os.path.abspath(__file__))
_MAT = _os.environ.get("SPOT_RL_MAT", _os.path.join(_HERE, "spot_policy.mat"))
_D = None


def _load():
    global _D
    if _D is None:
        m = _sio.loadmat(_MAT)
        def s(k):                                    # .mat scalar -> python float (any (1,1)/(1,) shape)
            return float(np.ravel(m[k])[0])
        _D = dict(W1=m["W1"], b1=m["b1"], W2=m["W2"], b2=m["b2"], W3=m["W3"], b3=m["b3"],
                  obs_mean=m["obs_mean"], obs_std=m["obs_std"],
                  BASE=np.ravel(m["BASE"]), BAND=np.ravel(m["BAND"]),
                  clip_obs=s("clip_obs"), ACOEF_HI=s("ACOEF_HI"), HSLACK_LO=s("HSLACK_LO"),
                  HSLACK_HI=s("HSLACK_HI"), KDOCK=s("KDOCK"), KBAND=s("KBAND"))
    return _D


def _build_obs(xR, xB, xU, rkoz_tar):
    """The 28-D observation -- identical to SpotDockEnv._obs() (full-obs branch)."""
    _, _, V, e = clf_rows(xR, xB, 1)
    _, _, h_tar = koz_row(xR, xB, rkoz_tar, 1, 1, 1, mRED)
    _, _, h_obs = koz_row(xR, xU, R_KOZ_OBS, 1, 1, 1, mRED)
    _, _, h_los = los_row(xR, xB, 1, 1, 1, IRED, 1)
    (_, _, h_vl), (_, _, h_va) = vel_rows(xR)
    return np.concatenate([
        e,
        [np.cos(xR[2]), np.sin(xR[2]), xR[3], xR[4], xR[5]],
        xR[0:2] - xB[0:2], xR[3:5] - xB[3:5], [xB[5]],
        xR[0:2] - xU[0:2], xR[3:5] - xU[3:5], [xU[5]],
        [h_tar, h_obs, h_los, h_vl, h_va],
        [V, rkoz_tar[0] - R_KOZ_TAR_MIN[0]],
    ])


def get_gains(x_red, x_black, x_obstacle, holding_radius=None):
    """states -> RL class-K gains (3x3) + k_dock.  numpy only; same interface as the
    torch bridge so call_python_policy.m / the Simulink block are unchanged."""
    D = _load()
    xR = np.asarray(x_red, dtype=np.float64).reshape(-1)[:6]      # robust to MATLAB row/col/2-D
    xB = np.asarray(x_black, dtype=np.float64).reshape(-1)[:6]
    xU = np.asarray(x_obstacle, dtype=np.float64).reshape(-1)[:6]
    if holding_radius is not None:
        hr = np.asarray(holding_radius, dtype=np.float64).reshape(-1)
        rkoz = hr[:2] if hr.size >= 2 else np.array([hr[0], hr[0]])
    else:
        rkoz = R_KOZ_TAR_INI

    obs = _build_obs(xR, xB, xU, rkoz).reshape(-1, 1)
    on = np.clip((obs - D["obs_mean"]) / D["obs_std"], -D["clip_obs"], D["clip_obs"])
    h = np.tanh(D["W1"] @ on + D["b1"])
    h = np.tanh(D["W2"] @ h + D["b2"])
    a = np.clip((D["W3"] @ h + D["b3"]).reshape(-1), -1.0, 1.0)

    grid = a[0:9].reshape(3, 3)
    g = D["BASE"][None, :] + D["BAND"][None, :] * grid
    g[:, 0:2] = np.clip(g[:, 0:2], 0.0, D["ACOEF_HI"])
    g[:, 2] = np.clip(g[:, 2], D["HSLACK_LO"], D["HSLACK_HI"])
    k_dock = float(max(0.1, D["KDOCK"] + D["KBAND"] * float(a[9])))
    return dict(gains=np.asarray(g, dtype=np.float64), k_dock=k_dock, success=True)


if __name__ == "__main__":
    xR, xB, xU = TEST_CASES[2]
    out = get_gains(xR, xB, xU)
    print("k_dock = %.3f" % out["k_dock"])
    print("gains =\n", np.round(out["gains"], 3))
'''

HEADER = ("# AUTO-GENERATED by make_slim.py from spot_env.py -- numpy-only inference (no torch).\n"
          "# Regenerate after retraining/re-exporting spot_policy.mat:  python make_slim.py\n")
open("spot_rl_policy.py", "w").write(HEADER + "".join(head) + SLIM)
print("wrote spot_rl_policy.py  (numpy-only; head %d lines + slim policy)" % len(head))
