"""Generate spot_rl_policy_slim.py -- numpy-only (no torch / SB3 / qpsolvers / gymnasium).

It takes spot_env's pure-numpy head (constants + CBF/CLF helpers, everything BEFORE the
gym class), strips the 3 heavy imports, and appends a .mat-weights policy. So the obs
builder is the SAME code as training and can't drift.
"""
import re

src = open("spot_env.py").read().splitlines(keepends=True)
cut = next(i for i, l in enumerate(src) if l.startswith("class SpotDockEnv"))
head = [l for l in src[:cut]
        if not re.match(r"(import gymnasium|from gymnasium|from qpsolvers)", l)]

SLIM = r'''

# ===================== slim policy (numpy-only, .mat weights) =====================
import os as _os
import scipy.io as _sio

_HERE = _os.path.dirname(_os.path.abspath(__file__))
_MAT = _os.environ.get("SPOT_RL_MAT", _os.path.join(_HERE, "spot_policy.mat"))
_D = None


def _load():
    global _D
    if _D is None:
        _D = _sio.loadmat(_MAT)
    return _D


def _build_obs(xR, xB, xU, rkoz_tar):
    """The 28-D observation -- identical to SpotDockEnv._obs() (full-obs branch)."""
    _, _, V, e = clf_rows(xR, xB, 1)
    _, _, h_tar = koz_row(xR, xB, rkoz_tar, 1, 1, 1, mRED)
    _, _, h_obs = koz_row(xR, xU, R_KOZ_OBS, 1, 1, 1, mRED)
    _, _, h_los = los_row(xR, xB, 1, 1, 1, IRED, 1)
    (_, _, h_vl), (_, _, h_va) = vel_rows(xR)
    return np.concatenate([
        e,
        [np.cos(xR[2]), np.sin(xR[2]), xR[3], xR[4], xR[5]],
        xR[0:2] - xB[0:2], xR[3:5] - xB[3:5], [xB[5]],
        xR[0:2] - xU[0:2], xR[3:5] - xU[3:5], [xU[5]],
        [h_tar, h_obs, h_los, h_vl, h_va],
        [V, rkoz_tar[0] - R_KOZ_TAR_MIN[0]],
    ])


def get_gains(x_red, x_black, x_obstacle, holding_radius=None):
    """states -> RL class-K gains (3x3) + k_dock.  numpy only; same interface as the
    torch bridge so call_python_policy.m / the Simulink block are unchanged."""
    D = _load()
    xR = np.asarray(x_red, float).ravel()[:6]
    xB = np.asarray(x_black, float).ravel()[:6]
    xU = np.asarray(x_obstacle, float).ravel()[:6]
    if holding_radius is not None:
        hr = np.asarray(holding_radius, float).ravel()
        rkoz = hr[:2] if hr.size >= 2 else np.array([hr[0], hr[0]])
    else:
        rkoz = R_KOZ_TAR_INI

    obs = _build_obs(xR, xB, xU, rkoz).reshape(-1, 1)
    on = np.clip((obs - D["obs_mean"]) / D["obs_std"], -float(D["clip_obs"]), float(D["clip_obs"]))
    h = np.tanh(D["W1"] @ on + D["b1"])
    h = np.tanh(D["W2"] @ h + D["b2"])
    a = np.clip((D["W3"] @ h + D["b3"]).ravel(), -1, 1)

    grid = a[0:9].reshape(3, 3)
    BASE = D["BASE"].ravel(); BAND = D["BAND"].ravel()
    g = BASE[None, :] + BAND[None, :] * grid
    g[:, 0:2] = np.clip(g[:, 0:2], 0.0, float(D["ACOEF_HI"]))
    g[:, 2] = np.clip(g[:, 2], float(D["HSLACK_LO"]), float(D["HSLACK_HI"]))
    k_dock = float(max(0.1, float(D["KDOCK"]) + float(D["KBAND"]) * a[9]))
    return dict(gains=np.asarray(g, float), k_dock=k_dock, success=True)


if __name__ == "__main__":
    xR, xB, xU = TEST_CASES[2]
    out = get_gains(xR, xB, xU)
    print("k_dock = %.3f" % out["k_dock"])
    print("gains =\n", np.round(out["gains"], 3))
'''

HEADER = ("# AUTO-GENERATED by make_slim.py from spot_env.py -- numpy-only inference (no torch).\n"
          "# Regenerate after retraining/re-exporting spot_policy.mat:  python make_slim.py\n")
open("spot_rl_policy.py", "w").write(HEADER + "".join(head) + SLIM)
print("wrote spot_rl_policy.py  (numpy-only; head %d lines + slim policy)" % len(head))
