# AUTO-GENERATED by make_slim.py from spot_env.py -- numpy-only inference (no torch).
# Regenerate after retraining/re-exporting spot_policy.mat:  python make_slim.py
"""
SPOT docking RL environment (gymnasium).

Scenario
--------
A chaser (RED) docks with a free-drifting target (BLACK) on a frictionless
air-bearing table while:
  - staying out of two moving elliptical keep-out zones (KOZ) -- one around the
    target (BLACK), one around an obstacle (BLUE),
  - keeping the target inside its camera field-of-view (LOS cone),
  - respecting velocity limits.

Control architecture
--------------------
Every step a CLF-CBF quadratic program (QP) turns the docking objective into a
safe force/torque command:
  - a Control Lyapunov Function (CLF) pulls the chaser toward the dock pose,
  - three Input-Constrained CBFs (ICCBFs) enforce the two KOZs and the LOS cone,
    each carrying an optimal-decay slack k>=0 that enters as (alpha+k)*h,
  - the velocity-limit CBFs are computed for the observation but (matching the
    MATLAB fcn()) are NOT part of the QP.

The RL agent chooses the ICCBF class-K gains and the CLF decay rate that make
this QP dock efficiently; `_decode` maps a [-1,1]^10 action to those gains.
Set `setconst=True` to pin the gains to fixed values instead (for testing /
MATLAB comparison).

All CBF/CLF rows below are closed-form Lie-derivative expressions, verified
against finite differences and the MATLAB build_iccbf_functions.m.
"""
import numpy as np

# ----------------------------- constants (from SPOT initializer) -----------
mRED, IRED = 12.137, 0.19816    # SPOT platform mass/inertia (MATLAB initializer)

U_MAX = 0.1*np.array([1.0, 1.0, 0.15])                 # [Fx Fy tau] limits
TORQUE_ARM = 0.07    # m, AVG SPOT thruster moment arm (~7 cm): torque is made by thrusters at this arm,
                     # so Ftotal = |F| + |tau|/arm (Ns-equiv) and propellant = integral of Ftotal dt.
TOF_CAP = 110.0      # s; SOFT time-of-flight cap. One-sided: docking up to here is free (gentle docking
                     # stays allowed, cuts FORCE like DE), only dawdling PAST it is penalized (reward+score).

FOV = np.deg2rad(40.0)
SENS_OFF = np.array([0.145-0.042, -0.0395])            # sensor_offset (planar)
SENS_NRM = np.array([1.0, 0.0])                        # sensor_normal
SENS_TGT = np.array([0.0825, 0.2516])                  # sensor_target (BLACK body)
DOCK_OFF = np.array([0.165, 0.427, -np.pi/2])          # docking_offset
R_KOZ_TAR_MIN = np.array([0.8, 0.42])
R_KOZ_TAR_INI = np.array([0.85, 0.85])
R_KOZ_OBS = np.array([0.43, 0.43])

# KOZ shrink (chart_495): proximity-gated contraction toward R_KOZ_TAR_MIN,
# triggered when the chaser HOLDS the dock point, NOT by elapsed time.
ETA  = np.sqrt(0.5)                                    # dock-hold position tol [m]
ZETA = np.deg2rad(10.0)                                # dock-hold attitude tol [rad]
T_S  = 4.0                                             # shrink time constant [s]
BETA = np.pi/2 - np.arctan2(DOCK_OFF[0], DOCK_OFF[1])  # dock direction on ellipse
V_MAX, AV_MAX = 0.1, np.deg2rad(8.0)

# docking CLF weight (sliding form, Run_Initializer.m): V=6I, lambda_dock=1
#   Q_dock = [[lambda^2 I, lambda V],[lambda V, V^2]]  (= [[I, 6I],[6I, 36I]])

_V_DOCK, _LAM_DOCK = 6*np.eye(3), 1.0
Q_DOCK = np.block([[_LAM_DOCK**2*np.eye(3), _LAM_DOCK*_V_DOCK],
                   [_LAM_DOCK*_V_DOCK,      _V_DOCK@_V_DOCK]])
K_DOCK = 5.0
K_VEL = 0.075
P_CLF = 10.0          # CLF slack penalty (p_clf in fcn())
P_CBF = 1e5           # CBF optimal-decay slack penalty (k weight in H, MATLAB)
XL, YL = 3.5, 2.4     # table extent (xLength, yLength)
DT = 0.05             # control/sim step [s] = 20 Hz (Run_Initializer baseRate)
T_MAX = 45.0
EPS = 1e-9
D2R = np.pi/180

# Deterministic scenarios from Run_Initializer.m: (x_RED_0, x_BLACK_0, x_BLUE_0).
# Each state is [x, y, theta, dx, dy, dtheta]; BLACK/BLUE drift force-free.
TEST_CASES = {
    0: (np.array([3.0, 2.0, 0.0, 0,0,0.0]),
        np.array([0.5, 0.5, 315*D2R, 0.01, 0.01, 1*D2R]),
        np.array([1.5, 1.25, 0.0, 0.015, 0.0075, 0.0])),
    1: (np.array([3.2, 1.8, 0.0, 0,0,0.0]),
        np.array([2.0, 2.2, 270*D2R, -0.005, -0.005, -2.5*D2R]),
        np.array([2.5, 1.25, 0.0, -0.01, -0.01, 0.0])),
    2: (np.array([1.5, 2.0, np.pi, 0,0,0.0]),
        np.array([2.2, 0.2, 270*D2R, -0.005, 0.005, 1.5*D2R]),
        np.array([2.0, 1.2, 0.0, -0.015, 0.0, 0.0])),
    
    3: (np.array([3.0, 2.0, 0.0, 0,0,0.0]),
        np.array([XL/2, YL/2, 90*D2R, 0,0,0.0]),
        np.array([0.0, 0.0, 0.0, 0,0,0.0])),
    4: (np.array([3.0, 2.0, 0.0, 0,0,0.0]),
        np.array([0.5, 0.5, 315*D2R, 0,0,0.0]),
        np.array([1.5, 1.25, 0.0, 0.015, 0.0075, 0.0])),
}
N_CASES = 3        # how many of the named TEST_CASES to CONSIDER (train-sample + eval over the
                   # first N_CASES only). All 5 stay defined; set back to len(TEST_CASES) for all.

# --- meta-RL domain randomization (hidden task params, sampled each reset) ---
# Dynamics (mRED, IRED, U_MAX) are held fixed at the values verified from
# MPC-data1.csv; only the task geometry varies, so the RNN must infer it.
DR_KOZ_SCALE   = (0.90, 1.10)     # target/obstacle keep-out ellipse size factor
DR_FOV_SCALE   = (0.85, 1.15)     # camera half-angle factor
DR_SENS_SCALE  = (0.90, 1.10)     # sensor offset / target-point factor
DR_SPIN_RANGE  = (np.deg2rad(0.5), np.deg2rad(2.5))   # BLACK initial spin rate
DR_POSE_JITTER = 0.15             # +/- m on initial chaser/target/obstacle pose
DR_ATT_JITTER  = np.deg2rad(20.0) # +/- rad on initial/goal attitudes

# random-pose (pose_random) sampling -- WIDENED to COVER the 5 named eval cases so
# they are in-distribution (case 1 spins 2.5 deg/s; cases 0/4 start ~2.9 m out, both
# outside the old random ranges, which is why pose_random eval'd badly on them).
POSE_SPIN_MAX  = np.deg2rad(3.0)  # max |target spin| for random poses (> case 1's 2.5)
POSE_DRIFT_MAX = 0.015            # max linear drift on target/obstacle (matches named cases)
POSE_FAR_FRAC  = 0.5              # fraction of layouts forced to a long (>2.2 m) approach
POSE_MIX_CASES = 0.30             # fraction of pose_random resets that use a NAMED eval case


def sample_pose_config(rng, margin=0.45):
    """Random VALID initial poses for the 3 bodies (positions+headings only;
    KOZ/FOV geometry unchanged). Chaser is placed clear of both keep-out zones,
    all bodies on the table; target/obstacle get small constant drift.

    Ranges WIDENED to cover the named eval cases: target spin up to POSE_SPIN_MAX
    (>2.5 deg/s) and -- on half the layouts -- a long (>2.2 m) chaser approach, so
    case-1-like spins and case-0/4-like distances are practiced, not out-of-dist."""
    def rand_xy():
        return np.array([rng.uniform(margin, XL-margin), rng.uniform(margin, YL-margin)])
    far = rng.random() < POSE_FAR_FRAC            # half: force a long approach (covers ~2.9 m)
    for _ in range(400):
        pB, pU, pR = rand_xy(), rand_xy(), rand_xy()
        d_RB = np.linalg.norm(pR-pB)
        if d_RB < R_KOZ_TAR_INI[0]+0.15:                   continue
        if far and d_RB < 2.2:                             continue   # bias to long approaches
        if np.linalg.norm(pR-pU) < R_KOZ_OBS[0]+0.15:      continue
        if np.linalg.norm(pB-pU) < R_KOZ_TAR_INI[0]+R_KOZ_OBS[0]+0.1: continue
        xR0 = np.array([pR[0], pR[1], rng.uniform(-np.pi, np.pi), 0, 0, 0.0])
        xB0 = np.array([pB[0], pB[1], rng.uniform(-np.pi, np.pi),
                        *rng.uniform(-POSE_DRIFT_MAX, POSE_DRIFT_MAX, 2),
                        rng.uniform(-POSE_SPIN_MAX, POSE_SPIN_MAX)])
        xU0 = np.array([pU[0], pU[1], rng.uniform(-np.pi, np.pi),
                        *rng.uniform(-POSE_DRIFT_MAX, POSE_DRIFT_MAX, 2), 0.0])
        return xR0, xB0, xU0
    return [a.copy() for a in TEST_CASES[4]]      # fallback (very unlikely)


# ----------------------------- planar-rotation helpers ---------------------
# Rmat and its 1st-3rd derivatives w.r.t. the angle (used to differentiate the
# rotating keep-out ellipse / sensor frame symbolically-by-hand).
def Rmat(t):   return np.array([[ np.cos(t), -np.sin(t)], [ np.sin(t),  np.cos(t)]])
def dRmat(t):  return np.array([[-np.sin(t), -np.cos(t)], [ np.cos(t), -np.sin(t)]])
def ddRmat(t): return np.array([[-np.cos(t),  np.sin(t)], [-np.sin(t), -np.cos(t)]])
def dddRmat(t):return np.array([[ np.sin(t),  np.cos(t)], [-np.cos(t),  np.sin(t)]])
def wrap(a):   return np.arctan2(np.sin(a), np.cos(a))


def propellant(u):
    """Real propellant rate (Ns-equivalent): translational |F| + rotational |tau|/arm.
    Torque counted at its true thruster-impulse cost -- the metric the RL should minimize."""
    return float(np.hypot(u[0], u[1]) + abs(u[2]) / TORQUE_ARM)


# ----------------------------- CBF / CLF rows (verified) -------------------
# Each ICCBF row is the relative-degree-2 cascade (N=2):
#     b1 = h_dot  + a0 * h
#     b2 = h_ddot + (a0+a1) h_dot + a0 a1 h  -  W      (W = input-constraint margin)
#     QP row:   -Lg(b2) . u  <=  Lf(b2) + a2 * b2
# and returns (A over [Fx,Fy,tau], b, h).

def koz_row(xR, xB, rkoz, a0, a1, a2, m):
    """Elliptical keep-out ICCBF on the translational channel.

    Barrier h = d' Q d - 1 >= 0 keeps the chaser outside the rotating keep-out
    ellipse around platform xB, where d = chaser-platform offset and Q is the
    inverse-ellipse metric in the platform frame (semi-axes rkoz).
    """
    # inverse-ellipse metric Q and its time derivatives (platform spin thd)
    S = np.diag(1.0/rkoz**2)
    th, thd = xB[2], xB[5]
    Rt = Rmat(th); Rtd = thd*dRmat(th); Rtdd = thd**2*ddRmat(th); Rtddd = thd**3*dddRmat(th)
    Q   = Rt@S@Rt.T
    Qd  = Rt@S@Rtd.T + Rtd@S@Rt.T
    Qdd = Rtdd@S@Rt.T + 2*Rtd@S@Rtd.T + Rt@S@Rtdd.T
    Qddd= Rtddd@S@Rt.T + 3*Rtdd@S@Rtd.T + 3*Rtd@S@Rtdd.T + Rt@S@Rtddd.T

    # barrier h and its derivatives along the relative motion (d, dd)
    d = xR[0:2]-xB[0:2]; dd = xR[3:5]-xB[3:5]
    h    = d@Q@d - 1
    hd   = 2*(d@Q@dd) + d@Qd@d
    hdd  = 2*(dd@Q@dd) + 4*(d@Qd@dd) + d@Qdd@d
    hddd = 6*(dd@Qd@dd) + 6*(d@Qdd@dd) + d@Qddd@d

    # input-constraint margin W (smoothed worst-case force authority) and its rate
    w = (2/m)*(d@Q); sj = np.sqrt(w**2+EPS**2); W = sj@(U_MAX[0:2])
    wd = (2/m)*(dd@Q+d@Qd); Wdot = np.sum(w*wd/sj*U_MAX[0:2])

    # ICCBF QP row  A u <= b
    b2 = hdd + (a0+a1)*hd + a0*a1*h - W
    Lf = hddd + (a0+a1)*hdd + a0*a1*hd - Wdot
    Lg = (1/m)*(4*(dd@Q) + 4*(d@Qd)) + (a0+a1)*(2/m)*(d@Q)   # 1x2 over [Fx,Fy]
    A = np.array([-Lg[0], -Lg[1], 0.0]); b = Lf + a2*b2
    return A, b, h


def los_row(xR, xB, a0, a1, a2, I, tv,
            fov=FOV, sens_off=SENS_OFF, sens_tgt=SENS_TGT, sens_nrm=SENS_NRM):
    """Field-of-view (line-of-sight) ICCBF on the torque channel.

    Barrier h = (r.e)^2 - cos^2(FOV) (r.r) >= 0 keeps the target feature point
    inside the camera cone, where r is the sensor->target vector and e the
    boresight, both in world frame. Sensor geometry (fov, offset, target point,
    normal) is overridable so the env can randomize it as a hidden meta-param.
    """
    thc, thcd = xR[2], xR[5]; tht, thtd = xB[2], xB[5]
    Rc = Rmat(thc); dRc = dRmat(thc); ddRc = ddRmat(thc); Rt = Rmat(tht); dRt = dRmat(tht)

    # LOS vector r (sensor->target point) and boresight e, plus angle derivatives
    r = xB[0:2] + Rt@sens_tgt - xR[0:2] - Rc@sens_off
    e = Rc@sens_nrm
    drdth = -dRc@sens_off; ddrddth = -ddRc@sens_off
    dedth =  dRc@sens_nrm; ddeddth =  ddRc@sens_nrm
    rdot = tv*(xB[3:5] + thtd*dRt@sens_tgt - xR[3:5])

    # time derivatives of r, e along the chaser rotation (thcd) + target drift
    rd = thcd*drdth + rdot; ed = thcd*dedth
    rdd = thcd**2*ddrddth;  edd = thcd**2*ddeddth
    rddd = -thcd**3*drdth;  eddd = -thcd**3*dedth

    # barrier h and derivatives;  'a' = r.e (the projection onto boresight)
    cF = np.cos(fov)**2
    a = r@e; ad = rd@e + r@ed; add = rdd@e + 2*(rd@ed) + r@edd
    addd = rddd@e + 3*(rdd@ed) + 3*(rd@edd) + r@eddd
    h    = a**2 - cF*(r@r)
    hd   = 2*a*ad - 2*cF*(r@rd)
    hdd  = 2*(ad**2 + a*add) - 2*cF*(rd@rd + r@rdd)
    hddd = 6*ad*add + 2*a*addd - 6*cF*(rd@rdd) - 2*cF*(r@rddd)

    # explicit partials w.r.t. chaser attitude (the only actuated d.o.f. here)
    dhdth = 2*a*(drdth@e + r@dedth) - 2*cF*(r@drdth)
    ddhddth = 2*((drdth@e + r@dedth)**2 + a*(ddrddth@e + 2*(drdth@dedth) + r@ddeddth)
                 - (drdth@drdth + r@ddrddth)*cF)
    M_xt = 2*((rdot@e)*(drdth@e + r@dedth) + a*(rdot@dedth) - cF*(rdot@drdth))

    # input-constraint margin W (torque authority) and its rate
    wT = dhdth/I; sT = np.sqrt(wT**2+EPS**2); W = sT*U_MAX[2]
    Wdot = (wT*((ddhddth*thcd + M_xt)/I)/sT)*U_MAX[2]

    # ICCBF QP row  A u <= b   (torque channel only)
    b2 = hdd + (a0+a1)*hd + a0*a1*h - W
    Lf = hddd + (a0+a1)*hdd + a0*a1*hd - Wdot
    Lg = (1/I)*(2*ddhddth*thcd + 2*M_xt + (a0+a1)*dhdth)
    A = np.array([0.0, 0.0, -Lg]); b = Lf + a2*b2
    return A, b, h


def clf_rows(xR, xB, tv, k_dock=K_DOCK):
    """Docking CLF row:  LgV . u - delta <= rhs   (delta = CLF slack).

    V = e' Q_DOCK e is the sliding-mode docking error to the moving dock pose
    (BLACK pose + DOCK_OFF). k_dock is the CLF decay rate (agent-modulated).
    Returns (LgV, rhs, V, e).
    """
    th = xB[2]; thd = xB[5]; R = Rmat(th); dR = dRmat(th)
    r_des = xB[0:2] + R@DOCK_OFF[0:2]; th_des = wrap(th + DOCK_OFF[2])
    v_des = xB[3:5] + thd*dR@DOCK_OFF[0:2]; om_des = thd
    e = np.array([xR[0]-r_des[0], xR[1]-r_des[1], wrap(xR[2]-th_des),
                  xR[3]-v_des[0], xR[4]-v_des[1], xR[5]-om_des])
    B = np.zeros((6,3)); B[3,0] = 1/mRED; B[4,1] = 1/mRED; B[5,2] = 1/IRED
    LfV = 2*e@Q_DOCK@np.array([xR[3],xR[4],xR[5],0,0,0])
    LgV = 2*e@Q_DOCK@B
    dVdt = tv*(-2*e@Q_DOCK@np.array([v_des[0],v_des[1],om_des,0,0,0]))
    V = e@Q_DOCK@e
    rhs = -LfV - dVdt - k_dock*V
    return LgV, rhs, V, e


def vel_rows(xR):
    """First-order velocity-limit CBFs -> (A_lin,b_lin,h_lin),(A_ang,b_ang,h_ang).

    Computed for the observation only; NOT added to the QP (matching fcn()).
    """
    vx, vy, om = xR[3], xR[4], xR[5]
    h_lin = V_MAX**2 - vx**2 - vy**2
    A_lin = np.array([2*vx/mRED, 2*vy/mRED, 0.0]); b_lin = K_VEL*h_lin
    h_ang = AV_MAX**2 - om**2
    A_ang = np.array([0.0, 0.0, 2*om/IRED]); b_ang = K_VEL*h_ang
    return (A_lin, b_lin, h_lin), (A_ang, b_ang, h_ang)


def shrink_koz(xR, xB, rkoz, rmin, gamma_step, eta=ETA, zeta=ZETA,
               dock_off=DOCK_OFF, beta=BETA):
    """Distance-gated KOZ shrink (chart_495 / cbf_rvd.shrink_koz).

    Contract the target keep-out ellipse toward rmin by gamma_step, but ONLY
    while the chaser is holding the dock point on the ellipse boundary within
    eta (position) and zeta (attitude). No dependence on elapsed time.
    """
    a, b = rkoz
    r_dock = Rmat(xB[2]) @ ((a*b/np.sqrt((a*np.sin(beta))**2 + (b*np.cos(beta))**2))
                            * np.array([np.cos(beta), np.sin(beta)]))
    x_des = np.array([xB[0]+r_dock[0], xB[1]+r_dock[1], xB[2]+dock_off[2]])
    pos_err2 = (xR[:2]-x_des[:2]) @ (xR[:2]-x_des[:2])
    th_err = abs(wrap(xR[2]-x_des[2]))
    if pos_err2 < eta**2 and th_err < zeta:
        rkoz = gamma_step*rkoz
    return np.maximum(rkoz, rmin)


def di_step(x, u, m, I, dt):
    """Exact double-integrator (air-bearing) step for one rigid body."""
    a = np.array([u[0]/m, u[1]/m, u[2]/I])
    xn = x.copy()
    xn[0:3] = x[0:3] + x[3:6]*dt + 0.5*a*dt*dt
    xn[3:6] = x[3:6] + a*dt
    xn[2] = wrap(xn[2])
    return xn


# ----------------------------- environment ---------------------------------


# ===================== slim policy (numpy-only, .mat weights) =====================
import os as _os
import scipy.io as _sio

_HERE = _os.path.dirname(_os.path.abspath(__file__))
_MAT = _os.environ.get("SPOT_RL_MAT", _os.path.join(_HERE, "spot_policy.mat"))
_D = None


def _load():
    global _D
    if _D is None:
        _D = _sio.loadmat(_MAT)
    return _D


def _build_obs(xR, xB, xU, rkoz_tar):
    """The 28-D observation -- identical to SpotDockEnv._obs() (full-obs branch)."""
    _, _, V, e = clf_rows(xR, xB, 1)
    _, _, h_tar = koz_row(xR, xB, rkoz_tar, 1, 1, 1, mRED)
    _, _, h_obs = koz_row(xR, xU, R_KOZ_OBS, 1, 1, 1, mRED)
    _, _, h_los = los_row(xR, xB, 1, 1, 1, IRED, 1)
    (_, _, h_vl), (_, _, h_va) = vel_rows(xR)
    return np.concatenate([
        e,
        [np.cos(xR[2]), np.sin(xR[2]), xR[3], xR[4], xR[5]],
        xR[0:2] - xB[0:2], xR[3:5] - xB[3:5], [xB[5]],
        xR[0:2] - xU[0:2], xR[3:5] - xU[3:5], [xU[5]],
        [h_tar, h_obs, h_los, h_vl, h_va],
        [V, rkoz_tar[0] - R_KOZ_TAR_MIN[0]],
    ])


def get_gains(x_red, x_black, x_obstacle, holding_radius=None):
    """states -> RL class-K gains (3x3) + k_dock.  numpy only; same interface as the
    torch bridge so call_python_policy.m / the Simulink block are unchanged."""
    D = _load()
    xR = np.asarray(x_red, float).ravel()[:6]
    xB = np.asarray(x_black, float).ravel()[:6]
    xU = np.asarray(x_obstacle, float).ravel()[:6]
    if holding_radius is not None:
        hr = np.asarray(holding_radius, float).ravel()
        rkoz = hr[:2] if hr.size >= 2 else np.array([hr[0], hr[0]])
    else:
        rkoz = R_KOZ_TAR_INI

    obs = _build_obs(xR, xB, xU, rkoz).reshape(-1, 1)
    on = np.clip((obs - D["obs_mean"]) / D["obs_std"], -float(D["clip_obs"]), float(D["clip_obs"]))
    h = np.tanh(D["W1"] @ on + D["b1"])
    h = np.tanh(D["W2"] @ h + D["b2"])
    a = np.clip((D["W3"] @ h + D["b3"]).ravel(), -1, 1)

    grid = a[0:9].reshape(3, 3)
    BASE = D["BASE"].ravel(); BAND = D["BAND"].ravel()
    g = BASE[None, :] + BAND[None, :] * grid
    g[:, 0:2] = np.clip(g[:, 0:2], 0.0, float(D["ACOEF_HI"]))
    g[:, 2] = np.clip(g[:, 2], float(D["HSLACK_LO"]), float(D["HSLACK_HI"]))
    k_dock = float(max(0.1, float(D["KDOCK"]) + float(D["KBAND"]) * a[9]))
    return dict(gains=np.asarray(g, float), k_dock=k_dock, success=True)


if __name__ == "__main__":
    xR, xB, xU = TEST_CASES[2]
    out = get_gains(xR, xB, xU)
    print("k_dock = %.3f" % out["k_dock"])
    print("gains =\n", np.round(out["gains"], 3))
